'''
#There are three cups on a table, at positions A, B, and C.
#At the start, there is a ball hidden under the cup at position B.
#However, I perform several swaps on the cups, which is notated as two letters.
#For example, if I swap the cups at positions A and B, I could notate this as
#AB or BA.

#Create a function that returns the letter position that the ball is at, once
#I finish swapping the cups. The swaps will be given to you as a list.
'''

# #if i is only ever ac or ca, pass and then print once ball stayed at pos b
# #as soon as ab, ba ,cb, or bc is called then it begins
# #should we just append to starting cup? 
# # BB, AC, AB, AC, CA


# def cup_swapping(swaps):
#     #ball starts at bb
#     #list generated by user [ab, ba, ac, ca, bc]
#     # if only ac or ca mentioned, ball stays at bb
#     # if other positions are mentioned then reactively position must change
#     # [ab, ba, ac, ca, bc]
#     # bb, ab is b mentioned? yes, then swap position
#     # now a, is a mentioned? yes ok then swap with letter mentioned
#     # now b, is b mentioned? no, ignore x2
#     # is b mentioned? yes, ok, swap with other letter
    
#     if any(starting_letter in swaps for i in swaps):
#         print(f"I'm getting closer!")
#     else:
#         print(f"You're gunna be rich")
# # "AC"=="CA" but output depends on ball position 
# # "BA" == "AB" but output depends on ball position "BC", ""


# cup_swapping(["AC","AC", "BA"])

# def cup_swapping(swaps):
#     cup_startB = "B" #starting position
#     # list_to_string = ''.join(swaps) #converting list into string
#     for swap_letters in swaps:
#         if cup_startB in swap_letters:
#             swap_letters.replace(cup_startB, '')


from re import S


def cup_swapping(input):
    start = 'B'
    t = ''

    for swap in input:
        if start in swap:
            store = swap.split(start)
            for i in store:
                t+=i
            print('start',start)
            start = 
    return start

final_cup = cup_swapping(["BA", "AB", "CA", "BB", "AB" "CA", "BC"])
print(final_cup)